name: Test Build

on:
  push:
    branches: main
    paths:
      - "**.h"
      - "**.cpp"
      - "**.yml"
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: 89dd0f4d241136b843fb55813b2f0fa6448c204d

jobs:
  test-build:
    runs-on: windows-latest
    strategy:
      matrix:
        preset:
          - debug
          - release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: build-${{ matrix.preset }}-msvc
          buildPreset: ${{ matrix.preset }}-msvc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SureOfStealing-${{ matrix.preset }}
          path: contrib/Plugin*/skse/plugins/
